drop table PESSOA
drop table FUNCIONARIO
drop table MARKETING
drop table OP
drop table BUSINESS
drop table DEV
drop table DESIGNER
drop table CLIENTE
drop table ESTABELECIMENTO
drop table ENTREGADOR
drop table TELEFONE_ESTABELECIMENTO
drop table COMPRA
drop table CARDAPIO
drop table ITEM
drop table ITEM_COMPRA